jobs:
- job: A
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: '# Write your powershell commands here.
        
        throw error e
        
        Write-Host "Hello World" '

- job: B
  dependsOn: A
  condition: and(SucceededWithIssues(A), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  steps:
  - script: echo this only runs for master