resources:
  - repo: self

trigger:
  - master

stages:
- stage: Deploy
  displayName: Deploy artifact
  jobs:
  - deployment: deploy
    displayName: Deploy artifact to the maven repo
    environment: 'Development'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: ls
            displayName: Publish decode package

