jobs:
- job: A
  steps:
  - script: echo hello

- job: B
  dependsOn: A
  condition: and(partiallySucceeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  steps:
  - script: echo this only runs for master